# Generated by Django 4.0.5 on 2022-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_produkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.IntegerField(default=6.66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default='opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
