# Generated by Django 4.0.5 on 2022-06-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_produkt_cena_produkt_opis_produkt_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='status',
            new_name='dostepnosc',
        ),
    ]
